name: "CI: Benchmark Release"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  benchmark_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libtbb-dev libsimdjson-dev libhwloc-dev

      - name: Build in Release mode with benchmarks
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DDSF_BENCHMARKS=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install
          cmake --build . -j$(nproc) --config Release

      - name: Run benchmarks
        working-directory: ${{ github.workspace }}/benchmark
        run: |
          for bench in *.out; do
            echo "Running $bench"
            ./$bench
          done